---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## README

This repository is for the Pycon Limerick 2020 Git workshop. 

- [Description](#Description)
- [Before the workshop](#Before-the-workshop)
  - [Installing Git](#Installing-Git)
  - [Getting an account on GitHub](#Getting-an-account-on-github)

### Description 

This workshop is an introduction to Git/GitHub. The material assumes no prior knowledge or use of Git. The aim of the material is to get participants familiar with the basics of using Git, backed by a GitHub remote repository. In particular we will explore

* Creating repositories
* Cloning and Forking
* Adding and modifying the repository
* Branching and Pull requests

The workshop will be interactive, encouraging participants to create and modify repositories throughout and working in small groups "as a team of developers".

Since this is PyCon there is some Python code in the material, although it won't actually matter if you don't feel comfortable with Python yet. They are small examples and it is not required that you have to write your own Python code from scratch. This is a workshop about Git, not Python specific, after all.

### Before the workshop

Before the workshop, please ensure that you have Git installed on your machine and an account on GitHub. 

### Installing Git

You can check whether you have git installed already in a shell

```bash
which git
## /usr/bin/git
```

and 

```bash
git --version
## git version 2.21.0
```

If you already have it, great! No need to install.

#### Windows

Install [Git for Windows](https://git-for-windows.github.io/), also known as "Git Bash"

#### MacOS

**Option 1** Install [Git](https://git-scm.com/downloads) from the git website

**Option 2** Use brew: `brew install git`

#### Linux

* Ubuntu or Debian `sudo apt-get install git`
* Fedora or RedHat `sudo yum install git`

### Getting an account on GitHub

Register an account with [GitHub](https://github.com). It's free. 
You can do things like upgrade to paid, join organizations etc in the future, so don't worry about any of that now. It might be worth thinking about the username though. 

Some tips:

* Incoporate your actual name
* Reuse your name from other contexts, e.g Twitter, Slack
* Pick a username you are comfortable sharing with boss and colleagues
* Shorter is better
* I would avoid uppercase, usernames are case sensitive
* When you get the chance, think about adding a picture. It doesn't have to 
be a headshot, but avoid the default random image.
